name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 00 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: Jeffreyjose29/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config Jeffreyjose29 github-actions
          git config jeffreyjose91@gmail.com github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
